// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	versioned "github.com/gardener/gardener/pkg/client/machine/clientset/versioned"
	internalinterfaces "github.com/gardener/gardener/pkg/client/machine/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/gardener/gardener/pkg/client/machine/listers/machine/v1alpha1"
	machinev1alpha1 "github.com/gardener/machine-controller-manager/pkg/apis/machine/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// KubeVirtMachineClassInformer provides access to a shared informer and lister for
// KubeVirtMachineClasses.
type KubeVirtMachineClassInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.KubeVirtMachineClassLister
}

type kubeVirtMachineClassInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewKubeVirtMachineClassInformer constructs a new informer for KubeVirtMachineClass type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewKubeVirtMachineClassInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredKubeVirtMachineClassInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredKubeVirtMachineClassInformer constructs a new informer for KubeVirtMachineClass type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredKubeVirtMachineClassInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MachineV1alpha1().KubeVirtMachineClasses(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MachineV1alpha1().KubeVirtMachineClasses(namespace).Watch(options)
			},
		},
		&machinev1alpha1.KubeVirtMachineClass{},
		resyncPeriod,
		indexers,
	)
}

func (f *kubeVirtMachineClassInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredKubeVirtMachineClassInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *kubeVirtMachineClassInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&machinev1alpha1.KubeVirtMachineClass{}, f.defaultInformer)
}

func (f *kubeVirtMachineClassInformer) Lister() v1alpha1.KubeVirtMachineClassLister {
	return v1alpha1.NewKubeVirtMachineClassLister(f.Informer().GetIndexer())
}
